spring:
  application:
    name: credit
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: demo

server:
  port: 8085
#  error:
#    include-stacktrace: NEVER

microservices:
  customer:
    urlPaths:
      getCustomer: http://localhost:8081/api/customers
  products:
    urlPaths:
      getProduct: http://localhost:8086/api/products